---
title: Publications
---

```{r setup, include=FALSE}
library(tidyverse)
library(here)

knitr::opts_chunk$set(echo=FALSE, message = FALSE, warning = FALSE)

```


<div class="row publications-page">

<div class="col-sm-2">
</div>

<div class="col-sm-10">


```{r}
# create the table data
publications <- readxl::read_xlsx(here("_data/publications.xlsx"))

publications_table <- publications %>%
  arrange(desc(year), type) %>%
  mutate(title = ifelse(!is.na(url), str_c("[", title, "](", url, ")"), title)) %>% #turn title into link
  #mutate(title = str_c("<span style='text-decoration: underline'>", title, "</span>")) %>% #underline title
  mutate(award = ifelse(is.na(award), "", str_c(
    "<i class='fa fa-trophy'></i><em> ", award, "</em> ·"
  )),
  pdf = ifelse(is.na(pdf), "", str_c(" <span class='publication-extra'>[pdf](", pdf, ")</span>")),
  materials = ifelse(is.na(materials), "", str_c(" · <span class='publication-extra'>[materials](", materials, ")</span>")),
  ebook = ifelse(is.na(ebook), "", str_c(" · <span class='publication-extra'>[e-book](", ebook, ")</span>")),
  blog = ifelse(is.na(blog), "", str_c(" · <span class='publication-extra'>[blog](", blog, ")</span>")),
  video = ifelse(is.na(video), "", str_c(" · <span class='publication-extra'>[video](", video, ")</span>")),
  bibtex = ifelse(is.na(bibtex), "", str_c(" · <span class='publication-extra'>[bibtex](", bibtex, ")</span>"))) %>% 
  mutate(citation = str_c("<span class=pub-title>", title, "</span><br>", 
                                 authors_full, "<br>",
                                 venue, "<br>",
                                 award, pdf, materials, ebook, blog, video, bibtex,
                                 sep = " ")
           
           ) %>%          
  mutate(citation = str_replace(citation, "Ulrik Lyngs", "_Ulrik Lyngs_")) # make my name bold

```

```{r results='asis'}
# draw a table with heading for each year
years <- publications$year %>% unique()

for (cur_year in years){
  publications_table %>% 
    filter(year == cur_year) %>% 
    select(type, citation) %>%
    knitr::kable(caption = cur_year) %>% 
    print()
}

```

</div>

</div> <!-- end row -->